## 1. Configuração e carregamento dos dados

In [1]:
import pandas as pd

In [2]:
df_slabel = pd.read_csv("dados/01_treino_sinais_vitais_sem_label.csv", header=None, names=['id', 'pSist', 'pDiast', 'qPA', 'pulso', 'resp', 'gravidade'])
df_label = pd.read_csv("dados/02_treino_sinais_vitais_com_label.csv", header=None, names=['id', 'pSist', 'pDiast', 'qPA', 'pulso', 'resp', 'gravidade', 'rotulo_saida'])

In [3]:
df_label.head()

,id,pSist,pDiast,qPA,pulso,resp,gravidade,rotulo_saida
0,1,13.592433,12.220855,8.416754,75.921057,21.635259,40.000000,2
1,2,15.775386,13.586879,8.725890,63.813564,19.718734,41.530427,2
2,3,3.649369,1.904802,0.000000,197.210213,19.045471,52.730745,3
3,4,17.264362,13.700638,8.733333,143.636181,17.621141,34.679911,2
4,5,12.705183,9.485389,1.747626,82.636672,12.209535,69.375882,3

In [4]:
df_slabel.head()

   id      pSist     pDiast       qPA       pulso       resp  gravidade
0   1  13.592433  12.220855  8.416754   75.921057  21.635259  40.000000
1   2  15.775386  13.586879  8.725890   63.813564  19.718734  41.530426
2   3   3.649369   1.904802  0.000000  197.210213  19.045471  52.730748
3   4  17.264362  13.700638  8.733333  143.636181  17.621141  34.679910
4   5  12.705183   9.485389  1.747626   82.636672  12.209535  69.375881

In [5]:
# colunas nao usadas
df_slabel = df_slabel.drop(columns=['pDiast', 'pSist'])
df_label = df_label.drop(columns=['pDiast', 'pSist'])

In [6]:
df_label.shape

(1500, 6)

## 2. Redes Neurais MLP